version: '3.9'

services:
  mongodb:
    image: mongo:5.0.8
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    
  api:
    build: .
    ports:
      - 5000:5000
    restart: always
    environment:
      - FLASK_ENV=development
      - MONGODB_DB=users
      - MONGODB_HOST=mongodb
      - MONGODB_USER=admin
      - MONGODB_PASSWORD=admin
    depends_on:
      - mongodb
    volumes:
      - ./application:/app/application
