repositories:
- name: twuni
  url: https://helm.twun.io
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: sealed-secrets
  url: https://bitnami-labs.github.io/sealed-secrets


releases:
- name: docker-registry
  namespace: docker-registry
  createNamespace: true
  chart: twuni/docker-registry
  version: 2.2.3
  values:
    - values/docker-registry/values.yaml

- name: ingress-nginx
  namespace: ingress-nginx
  createNamespace: true
  chart: ingress-nginx/ingress-nginx
  version: 4.9.1
  values:
    - values/ingress-nginx/values.yaml

- name: sealed-secrets
  namespace: kube-system
  createNamespace: true
  chart: sealed-secrets/sealed-secrets
  version: 2.17.0
  values:
    - values/sealed-secrets/values.yaml
  set:
    - name: fullnameOverride
      value: sealed-secrets-controller
