apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: restapi-flask
  name: restapi-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restapi-flask
  template:
    metadata:
      labels:
        app: restapi-flask
    spec:
      containers:
      - image: restapi-flask
        name: restapi-flask
        imagePullPolicy: Never
        env:
        - name: FLASK_ENV
          value: "development"
        - name: MONGODB_DB
          value: "users"
        - name: MONGODB_HOST
          value: "mongodb"
        - name: MONGODB_USER
          value: "admin"
        - name: MONGODB_PASSWORD
          value: "admin"
